MyNUnit
IvanMoskalenko/III-Semester-HW pull request #6
Opened 2021-11-13 12:39 UTC by IvanMoskalenko

2021-12-01 20:13 UTC, yurii-litvinov requested changes

2021-12-01 20:13 UTC, yurii-litvinov commented on src/MyNUnit/.idea/.idea.MyNUnit/.idea/.gitignore
> +# Default ignored files
Папку .idea в Райдере вообще не надо выкладывать, добавьте её в .gitignore.

2021-12-01 20:13 UTC, yurii-litvinov commented on src/MyNUnit/Attributes/Attributes.csproj
> +        <TargetFramework>net5.0</TargetFramework>
Стоит перейти на .NET 6 и C# 10, он гораздо удобнее C# 9

2021-12-01 20:13 UTC, yurii-litvinov commented on src/MyNUnit/Attributes/After.cs
> +    public class After: Attribute
Стоит тут указать AttributeUsage, чтобы нельзя было вешать этот атрибут на параметры методов, например

2021-12-01 20:13 UTC, yurii-litvinov commented on src/MyNUnit/MyNUnit/MyNUnit.cs
> +                .Select(Assembly.LoadFrom)
Можно было грузить сборки параллельно, причём с PLINQ это дописать одну строчку просто

2021-12-01 20:13 UTC, yurii-litvinov commented on src/MyNUnit/MyNUnit/MyNUnit.cs
> +            _methods = new MethodsLists();
Хм, а гонки по _methods так не будет? Вы же запускаете сразу много тестовых классов

2021-12-01 20:13 UTC, yurii-litvinov commented on src/MyNUnit/TestsSet/MyNUnitTests.cs
> +    public class Tests
Вообще, плохая идея тестировать многопоточный запуск нескольких тестовых классов на одном тестовом классе. Тесты, конечно, пройдут, но...

2021-12-01 20:13 UTC, yurii-litvinov commented on src/MyNUnit/MyNUnit/MyNUnit.cs
> +                TestsInformation.Enqueue(new TestInformation(method.Name, "Failed", e.Message, 0));
Это скорее не тест failed, это errored или что-то такое. Тест ведь даже не запустился.

2021-12-01 20:13 UTC, yurii-litvinov commented on src/MyNUnit/MyNUnit/MyNUnit.cs
> +                    : new TestInformation(method.Name, "Passed", null, stopWatch.ElapsedMilliseconds);
Я бы статут теста сделал enum-ом, потому что если в трёх местах будет "Passed", а в одном "Passd", то случится печаль, а компилятор Вам ничем не поможет.

2021-12-01 20:13 UTC, yurii-litvinov commented on src/MyNUnit/MyNUnit/MyNUnit.cs
> +                TestAfterOrBefore(type, _methods.Before);
Не-а, TestAfterOrBefore должен принимать уже инстанс. Потому что они обычно выставляют состояние у тестового объекта. Плохо, если мы проинициализировали один объект, а запустили тест в другом.

2021-12-02 21:23 UTC, merged

2021-12-02 21:28 UTC, IvanMoskalenko commented
.